const Errors = {
    "001": {"description": "Preencha os campos corretamente"}
}


const HttpErrors = {
    "001": {"description":"Erro inesperado ocorreu"},
    "100": {"description":"Continue"},
    "101": {"description":"Switching Protocols"},
    "102": {"description":"Processing"},
    "200": {"description":"OK"},
    "201": {"description":"Created"},
    "202": {"description":"Accepted"},
    "203": {"description":"Non-authoritative Information"},
    "204": {"description":"No Content"},
    "205": {"description":"Reset Content"},
    "206": {"description":"Partial Content"},
    "207": {"description":"Multi-Status"},
    "208": {"description":"Already Reported"},
    "226": {"description":"IM Used"},
    "300": {"description":"Multiple Choices"},
    "301": {"description":"Moved Permanently"},
    "302": {"description":"Found"},
    "303": {"description":"See Other"},
    "304": {"description":"Not Modified"},
    "305": {"description":"Use Proxy"},
    "307": {"description":"Temporary Redirect"},
    "308": {"description":"Permanent Redirect"},
    "400": {"description":"Bad Request"},
    "401": {"description":"Unauthorized"},
    "402": {"description":"Payment Required"},
    "403": {"description":"Forbidden"},
    "404": {"description":"Não encontrado"},
    "405": {"description":"Method Not Allowed"},
    "406": {"description":"Not Acceptable"},
    "407": {"description":"Proxy Authentication Required"},
    "408": {"description":"Request Timeout"},
    "409": {"description":"Conflict"},
    "410": {"description":"Gone"},
    "411": {"description":"Length Required"},
    "412": {"description":"Precondition Failed"},
    "413": {"description":"Payload Too Large"},
    "414": {"description":"Request-URI Too Long"},
    "415": {"description":"Unsupported Media Type"},
    "416": {"description":"Requested Range Not Satisfiable"},
    "417": {"description":"Expectation Failed"},
    "418": {"description":"I'm a teapot"},
    "421": {"description":"Misdirected Request"},
    "422": {"description":"Unprocessable Entity"},
    "423": {"description":"Locked"},
    "424": {"description":"Failed Dependency"},
    "426": {"description":"Upgrade Required"},
    "428": {"description":"Precondition Required"},
    "429": {"description":"Too Many Requests"},
    "431": {"description":"Request Header Fields Too Large"},
    "444": {"description":"Connection Closed Without Response"},
    "451": {"description":"Unavailable For Legal Reasons"},
    "499": {"description":"Client Closed Request"},
    "500": {"description":"Internal Server Error"},
    "501": {"description":"Not Implemented"},
    "502": {"description":"Bad Gateway"},
    "503": {"description":"Service Unavailable"},
    "504": {"description":"Gateway Timeout"},
    "505": {"description":"HTTP Version Not Supported"},
    "506": {"description":"Variant Also Negotiates"},
    "507": {"description":"Insufficient Storage"},
    "508": {"description":"Loop Detected"},
    "510": {"description":"Not Extended"},
    "511": {"description":"Network Authentication Required"},
    "599": {"description":"Network Connect Timeout Error"}
}


export default {HttpErrors, Errors}